// Generated by CoffeeScript 1.3.3
(function() {
  var app, express;

  express = require('express');

  app = express.createServer();

  app.get('/', function(req, res) {
    return res.render(__dirname + '/../views/index.jade');
  });

  app.set("view options", {
    layout: false
  });

  app.configure(function() {
    app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
    app.use(express.methodOverride());
    app.use(express.bodyParser());
    app.use(app.router);
    return app.use(express["static"](__dirname + '/../static'));
  });

  console.log("Running on port 3000");

  app.listen(3000);

}).call(this);
